# Configuration for gitpod.io
# To run on gitpod open https://gitpod.io/?autostart=false# followed by the github URL of your project
# e.g. https://gitpod.io/?autostart=false#https://github.com/hedera-dev/hedera-tutorial-demo-base-template
image: gitpod/workspace-full

tasks:
  - name: config_eliza
    init: |
      (
        set -e
        ./util/02-config-eliza.sh
        gp sync-done config_eliza
      )
  - name: install_eliza
    init: |
      (
        set -e
        ./util/01-install-eliza.sh
        gp sync-done install_eliza
      )
  - name: run_eliza
    init: |
      (
        set -e
        gp sync-await config_eliza
        gp sync-await install_eliza
        ./util/03-run-eliza-server.sh
        gp sync-done run_eliza
      )
  - name: run_client_eliza
    init: |
      (
        set -e
        gp sync-await run_eliza
        ./util/04-run-eliza-client.sh
        gp sync-done run_client_eliza
      )

ports:
  - port: 3000
    protocol: http
    visibility: public
    onOpen: notify
  - port: 5173
    protocol: http
    visibility: public
    onOpen: open-browser
